namespace TRIAL.MicrosoftEntityFrameworkCoreSqlServer2;

internal partial class Program
{
    static readonly string _QUERY_BASE = @"
SELECT A.EFOLDERKEY,A.MN18_CODIGO2 AS 'CODIGOVC',A.MN18_NOMBRE AS 'NOMBRE' FROM MN18_PRESTACIONFONASAUCO A (NOLOCK)
INNER JOIN [_TOPEIMED_H1] B ON A.MN18_CODIGO2 LIKE '%'+ B.CODIGOVC
WHERE A.DELETEDDATE IS NULL
ORDER BY A.MN18_CODIGO2,A.EFOLDERKEY;
SELECT A.EFOLDERKEY,A.MN18_CODIGO2 AS 'CODIGOVC',A.MN18_NOMBRE AS 'NOMBRE' FROM MN18_PRESTACIONFONASAUCO A (NOLOCK)
INNER JOIN [_TOPEIMED_H2] B ON A.MN18_CODIGO2 LIKE '%'+ B.CODIGOVC
WHERE A.DELETEDDATE IS NULL
ORDER BY A.MN18_CODIGO2,A.EFOLDERKEY;
SELECT A.EFOLDERKEY,A.MN18_CODIGO2 AS 'CODIGOVC',A.MN18_NOMBRE AS 'NOMBRE' FROM MN18_PRESTACIONFONASAUCO A (NOLOCK)
INNER JOIN [_TOPEIMED_H3] B ON A.MN18_CODIGO2 LIKE '%'+ B.CODIGOVC
WHERE A.DELETEDDATE IS NULL
ORDER BY A.MN18_CODIGO2,A.EFOLDERKEY;
SELECT A.EFOLDERKEY,A.MN18_CODIGO2 AS 'CODIGOVC',A.MN18_NOMBRE AS 'NOMBRE' FROM MN18_PRESTACIONFONASAUCO A (NOLOCK)
INNER JOIN [_TOPEIMED_H4] B ON A.MN18_CODIGO2 LIKE '%'+ B.CODIGOVC
WHERE A.DELETEDDATE IS NULL
ORDER BY A.MN18_CODIGO2,A.EFOLDERKEY;
SELECT A.EFOLDERKEY,A.MN18_CODIGO2 AS 'CODIGOVC',A.MN18_NOMBRE AS 'NOMBRE' FROM MN18_PRESTACIONFONASAUCO A (NOLOCK)
INNER JOIN [_TOPEIMED_H5] B ON A.MN18_CODIGO2 LIKE '%'+ B.CODIGOVC
WHERE A.DELETEDDATE IS NULL
ORDER BY A.MN18_CODIGO2,A.EFOLDERKEY;
SELECT A.EFOLDERKEY,A.MN18_CODIGO2 AS 'CODIGOVC',A.MN18_NOMBRE AS 'NOMBRE' FROM MN18_PRESTACIONFONASAUCO A (NOLOCK)
INNER JOIN [_TOPEIMED_H6] B ON A.MN18_CODIGO2 LIKE '%'+ B.CODIGOVC
WHERE A.DELETEDDATE IS NULL
ORDER BY A.MN18_CODIGO2,A.EFOLDERKEY;
SELECT A.EFOLDERKEY,A.MN18_CODIGO2 AS 'CODIGOVC',A.MN18_NOMBRE AS 'NOMBRE' FROM MN18_PRESTACIONFONASAUCO A (NOLOCK)
INNER JOIN [_TOPEIMED_H7] B ON A.MN18_CODIGO2 LIKE '%'+ B.CODIGOVC
WHERE A.DELETEDDATE IS NULL
ORDER BY A.MN18_CODIGO2,A.EFOLDERKEY;
";
    static readonly string _QUERY_UPDATE = @"

UPDATE MN58_TOPEIMEDDETALLE SET
DELETEDDATE = GETDATE()
WHERE DELETEDDATE IS NULL
AND MN58_TOPEIMED IN (
	SELECT EFOLDERKEY FROM MN57_TOPEIMED (NOLOCK)
	WHERE DELETEDDATE IS NULL
	AND MN57_PLAN= @_PLAN
)
;
UPDATE MN57_TOPEIMED SET
DELETEDDATE = GETDATE()
WHERE DELETEDDATE IS NULL
AND MN57_PLAN= @_PLAN
;
";

    static readonly string _QUERY_MN57 = @"
INSERT INTO [MN57_TOPEIMED]
           ([CREATEDDATE]
           ,[MN57_NOMBRE]
           ,[MN57_CANTIDAD]
           ,[MN57_PLAN]
           ,[MN57_TIEMPO])
     VALUES
           (GETDATE()
           ,@MN57_NOMBRE
           ,@MN57_CANTIDAD
           ,@MN57_PLAN
           ,@MN57_TIEMPO)
;
SELECT SCOPE_IDENTITY()
;
";
    static readonly string _QUERY_MN58 = @"
INSERT INTO [MN58_TOPEIMEDDETALLE]
           ([CREATEDDATE]
           ,[MN58_FONASA]
           ,[MN58_TOPEIMED])
     VALUES
           (GETDATE()
           ,@MN58_FONASA
           ,@MN58_TOPEIMED)
;
";

    static readonly string[] _NOMBRES = [
"Consultas Mensuales"
,"Consultas Anuales"
,"Ex. Laboratorio 1 Mensual"
,"Ex. Laboratorio 1 Anual"
,"Ex. Laboratorio 2 Mensual"
,"Ex. Laboratorio 2 Anual"
,"Imagenología Mensual"
,"Imagenología Anual"
,"Psicología Psquiatría Mensual"
,"Psicología Psquiatría Anual"
,"Fonoaudiología Mensual"
,"Fonoaudiología Anual"
,"Kinesiología Mensual"
,"Kinesiología Anual"
        ];

    static readonly byte[] _TIEMPOS = [
2
,1
,2
,1
,2
,1
,2
,1
,2
,1
,2
,1
,2
,1
    ];
    static readonly byte[] _CANTIDADES = [
2
,10
,1
,4
,2
,8
,1
,6
,4
,12
,8
,24
,12
,36
        ];
    static readonly byte[] _TABLAS = [
0
,0
,1
,1
,2
,2
,3
,3
,4
,4
,5
,5
,6
,6
    ];
}