//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace imL.Resource.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("imL.Resource.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @charset &quot;UTF-8&quot;;
        ////*!
        /// * Bootstrap v5.1.3 (https://getbootstrap.com/)
        /// * Copyright 2011-2021 The Bootstrap Authors
        /// * Copyright 2011-2021 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/main/LICENSE)
        /// */
        ///:root {
        ///    --bs-blue: #0d6efd;
        ///    --bs-indigo: #6610f2;
        ///    --bs-purple: #6f42c1;
        ///    --bs-pink: #d63384;
        ///    --bs-red: #dc3545;
        ///    --bs-orange: #fd7e14;
        ///    --bs-yellow: #ffc107;
        ///    --bs-green: #198754;
        ///    --bs-teal: #20c997;
        ///    --bs-cyan: #0dcaf0;
        ///    --bs-white: #fff;
        ///   [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CSS_bootstrap {
            get {
                return ResourceManager.GetString("CSS_bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;alert alert-danger bg-gradient&quot; role=&quot;alert&quot;&gt;
        ///    Proceso con errores.
        ///&lt;/div&gt;.
        /// </summary>
        internal static string HTML_danger {
            get {
                return ResourceManager.GetString("HTML_danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!doctype html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;Resumen de proceso.&quot;&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;Ricardo Llamocca&quot;&gt;
        ///    &lt;meta name=&quot;generator&quot; content=&quot;Richie 84.10.2&quot;&gt;
        ///    &lt;title&gt;Resume:&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body class=&quot;bg-light&quot;&gt;
        ///    &lt;div class=&quot;container-fluid&quot;&gt;
        ///        &lt;div class=&quot;bd-heading sticky-xl-top align-self-start mt-5 mb-3 mt-xl-0 mb-xl-2&quot;&gt;
        ///        [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HTML_resume {
            get {
                return ResourceManager.GetString("HTML_resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;alert alert-success bg-gradient&quot; role=&quot;alert&quot;&gt;
        ///    Proceso completado.
        ///&lt;/div&gt;.
        /// </summary>
        internal static string HTML_success {
            get {
                return ResourceManager.GetString("HTML_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&quot;alert alert-warning bg-gradient&quot; role=&quot;alert&quot;&gt;
        ///    Proceso completado sin diferencias.
        ///&lt;/div&gt;.
        /// </summary>
        internal static string HTML_warning {
            get {
                return ResourceManager.GetString("HTML_warning", resourceCulture);
            }
        }
    }
}
